### ISSUE TITLE
点击🔍Bug

### ISSUE THREAD

**Issue by binx6** [hushenghao/AndroidEasterEggs#135]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.2.2

### Bug description / Bug 描述

[Bug] App Crash: NoSuchMethodError

Device: Redmi K20 Pro (Xiaomi - raphael), SDK: 30 (11), App: 2.2.2 (36)

java.lang.NoSuchMethodError: No static method performImeAction$default(Landroidx/compose/ui/semantics/SemanticsPropertyReceiver;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V in class Lr1/s; or its super classes (declaration of 'r1.s' appears in base.apk)
	at a0.h0.a(SourceFile:184)
	at a0.h0.i0(SourceFile:3)
	at r1.c.M(SourceFile:3)
	at s.x0.a(SourceFile:249)
	at s.x0.m(SourceFile:34)
	at h0.k.d(SourceFile:60)
	at r0.y.a(SourceFile:48)
	at r0.z.c(SourceFile:153)
	at n1.k1.a(SourceFile:3)
	at androidx.compose.ui.node.a.o(SourceFile:43)
	at h0.t.m(SourceFile:110)
	at r1.n.b(SourceFile:34)
	at r1.n.l(SourceFile:15)
	at r1.n.g(SourceFile:27)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:61)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.a0(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:69)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:95)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.a0(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.B(SourceFile:143)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.w(SourceFile:36)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.T(SourceFile:17)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.U(SourceFile:7)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.X(SourceFile:111)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.u(SourceFile:153)
	at androidx.compose.ui.platform.n0.h(SourceFile:1)
	at o8.a.w(SourceFile:9)
	at d9.e0.run(SourceFile:115)
	at androidx.compose.ui.platform.e1.J(SourceFile:7)
	at androidx.compose.ui.platform.d1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
	Suppressed: i9.f: [androidx.compose.ui.platform.e2@368d4eb, h0.f@d447248, m1{Cancelling}@ca6c8e1, e1@33e4606]

### Expected behavior / 预期行为

none

### Actual behavior / 实际行为

none

### Steps to reproduce / 复现步骤

1.打开Easter Eggs
2.点击那个搜索图标，它自己弹出来的

### UI / OS

MIUI 12.5.6

### Android Version / Android 版本

11

### Additional info / 额外信息

似乎是缺少静态方法

**Comment by binx6** [comment]
**复现视频**↓

https://github.com/hushenghao/AndroidEasterEggs/assets/123862842/e2401bd7-741e-4e7d-a463-020578e237b5

**Comment by hushenghao** [comment]
这是一个遗留问题，以为只是个偶先的崩溃，看来在不同的设备上表现还不同
ref: https://issuetracker.google.com/issues/302680504

**Comment by hushenghao** [comment]
Fixed: https://issuetracker.google.com/issues/302680504#comment6

**Comment by binx6** [comment]
> Fixed, 安装最新的Beta版本
> commit: https://github.com/hushenghao/AndroidEasterEggs/commit/2a696ef06e2510ae2d1cd01ab4d9a50e11bf7d36
> ref: https://issuetracker.google.com/issues/302680504#comment6

**Beta版本经测试已经没问题了**👌
