### ISSUE TITLE
[Bug] App Crash: NoSuchMethodError

### ISSUE THREAD

**Issue by johnmengistu** [hushenghao/AndroidEasterEggs#140]
```
Device: moto g pure (motorola - ellis), SDK: 31 (12), App: 2.2.2 (36)

java.lang.NoSuchMethodError: No static method performImeAction$default(Landroidx/compose/ui/semantics/SemanticsPropertyReceiver;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V in class Lr1/s; or its super classes (declaration of 'r1.s' appears in /data/app/~~jy8KLzLzmTZlHttv1_nh9w==/com.dede.android_eggs-UqE1gdqMNwGy3jAhKvoKew==/base.apk)
	at a0.h0.a(SourceFile:184)
	at a0.h0.i0(SourceFile:3)
	at r1.c.M(SourceFile:3)
	at s.x0.a(SourceFile:249)
	at s.x0.m(SourceFile:34)
	at h0.k.d(SourceFile:60)
	at r0.y.a(SourceFile:48)
	at r0.z.c(SourceFile:153)
	at n1.k1.a(SourceFile:3)
	at androidx.compose.ui.node.a.o(SourceFile:43)
	at h0.t.m(SourceFile:110)
	at r1.n.b(SourceFile:34)
	at r1.n.l(SourceFile:15)
	at r1.n.g(SourceFile:27)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:61)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.a0(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:69)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:95)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.a0(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.B(SourceFile:143)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.w(SourceFile:36)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.T(SourceFile:17)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.U(SourceFile:7)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.X(SourceFile:111)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.u(SourceFile:153)
	at androidx.compose.ui.platform.n0.h(SourceFile:1)
	at o8.a.w(SourceFile:9)
	at d9.e0.run(SourceFile:115)
	at androidx.compose.ui.platform.e1.J(SourceFile:7)
	at androidx.compose.ui.platform.d1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
	Suppressed: i9.f: [androidx.compose.ui.platform.e2@1503500, h0.f@d4cc139, m1{Cancelling}@7a3d37e, e1@ca5a0df]

```

**Comment by hushenghao** [comment]
It’s fixed, try Update to last Bate Version在 2024年1月3日，02:46，johnnie mengistu ***@***.***> 写道：﻿
Device: moto g pure (motorola - ellis), SDK: 31 (12), App: 2.2.2 (36)

java.lang.NoSuchMethodError: No static method performImeAction$default(Landroidx/compose/ui/semantics/SemanticsPropertyReceiver;Ljava/lang/String;Lkotlin/jvm/functions/Function0;ILjava/lang/Object;)V in class Lr1/s; or its super classes (declaration of 'r1.s' appears in /data/app/~~jy8KLzLzmTZlHttv1_nh9w==/com.dede.android_eggs-UqE1gdqMNwGy3jAhKvoKew==/base.apk)
	at a0.h0.a(SourceFile:184)
	at a0.h0.i0(SourceFile:3)
	at r1.c.M(SourceFile:3)
	at s.x0.a(SourceFile:249)
	at s.x0.m(SourceFile:34)
	at h0.k.d(SourceFile:60)
	at r0.y.a(SourceFile:48)
	at r0.z.c(SourceFile:153)
	at n1.k1.a(SourceFile:3)
	at androidx.compose.ui.node.a.o(SourceFile:43)
	at h0.t.m(SourceFile:110)
	at r1.n.b(SourceFile:34)
	at r1.n.l(SourceFile:15)
	at r1.n.g(SourceFile:27)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:61)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.a0(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:69)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.y(SourceFile:95)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.a0(SourceFile:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.B(SourceFile:143)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.w(SourceFile:36)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.T(SourceFile:17)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.U(SourceFile:7)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.X(SourceFile:111)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.u(SourceFile:153)
	at androidx.compose.ui.platform.n0.h(SourceFile:1)
	at o8.a.w(SourceFile:9)
	at d9.e0.run(SourceFile:115)
	at androidx.compose.ui.platform.e1.J(SourceFile:7)
	at androidx.compose.ui.platform.d1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
	Suppressed: i9.f: ***@***.***, ***@***.***, ***@***.***, ***@***.***
