### ISSUE TITLE
[Bug] App Crash: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dxuser114** [hushenghao/AndroidEasterEggs#150]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of Easter Eggs. / 我正在使用 Easter Eggs 的最新版本。

### Easter Eggs version / Easter Eggs 版本

v2.2.2

### Bug description / Bug 描述

在宠物列表中只剩下一个时，长按那个宠物，快速点击两次叉号，出现两个对话框，点击两次确认后应用崩溃。

### Expected behavior / 预期行为

不会发生任何事。

### Actual behavior / 实际行为

结果崩溃了：
Device: tablePC (tablePC - tablePC), SDK: 30 (11), App: 2.2.2 (36)

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at x3.g.onClick(SourceFile:98)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:174)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7945)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Steps to reproduce / 复现步骤

1. 长按电源键打开菜单
2. 点击右上角三个点，再选择添加控件
3. 选择“查看其他应用”
4. 选择“paint chips”
5. 把三个全都选择，然后点击“保存”
6. 把电源键菜单3个控件中的两个控件开启
7. 等待应用通知
8. 应用通知后，再次长按电源键菜单
9. 长按任意一个控件
10. 在打开的界面中长按一个宠物（确保只有一个宠物）
11. 快速点击两次叉号
12. 点击两次确认
13. 应用崩溃

### UI / OS

AOSP

### Android Version / Android 版本

11

**Comment by hushenghao** [comment]
ref: 7bd931144cdf9f72ea33c601b0cd9325455a27b1
