### ISSUE TITLE
Fix language settings for XIaomi 11 Lite 5G NE with android 13

### ISSUE THREAD

**Issue by LoryPelli** [hushenghao/AndroidEasterEggs#22]
It redirects to phone settings but it crash

**Comment by hushenghao** [comment]
**This MIUI Settings issue**, I am unable to handle this issue.

**All Xiaomi Android 13 devices can reproduce this issue**.
This is the system log:
```
09:39:18.988 AndroidRuntime           E  FATAL EXCEPTION: main
                                         Process: com.android.settings, PID: 14134
                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                         	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3817)
                                         	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
                                         	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                         	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                         	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                         	at android.os.Looper.loopOnce(Looper.java:210)
                                         	at android.os.Looper.loop(Looper.java:299)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8237)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                         	at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:75)
                                         	at android.app.Activity.performCreate(Activity.java:8516)
                                         	at android.app.Activity.performCreate(Activity.java:8480)
                                         	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
                                         	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3798)
                                         	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963) 
                                         	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                         	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                         	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381) 
                                         	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                         	at android.os.Looper.loopOnce(Looper.java:210) 
                                         	at android.os.Looper.loop(Looper.java:299) 
                                         	at android.app.ActivityThread.main(ActivityThread.java:8237) 
                                         	at java.lang.reflect.Method.invoke(Native Method) 
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
```

**Comment by hushenghao** [comment]
I have reported this issue to the MIUI community.

https://s.xiaomi.cn/c/SmDF5Tb9
