### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by raymendus** [hushenghao/AndroidEasterEggs#250]
```
Device: M2101K6G (Redmi - sweet), SDK: 33 (13), App: 2.5.0 (40)

java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.a.u(SourceFile:3)
	at androidx.compose.ui.graphics.a.b(SourceFile:484)
	at k0.v.b(SourceFile:17)
	at m0.c.a(SourceFile:18)
	at m0.c.j(SourceFile:44)
	at A0.L.j(SourceFile:16)
	at m0.g.j(SourceFile:60)
	at v.q.a(SourceFile:37)
	at v.q.l(SourceFile:10)
	at h0.e.e(SourceFile:3)
	at A0.L.b(SourceFile:52)
	at A0.j0.E0(SourceFile:55)
	at A0.j0.C0(SourceFile:30)
	at A0.E.U0(SourceFile:6)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at A0.E.U0(SourceFile:6)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at A0.E.U0(SourceFile:6)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at v.U.b(SourceFile:324)
	at v.U.c(SourceFile:55)
	at C3.e.u(SourceFile:114)
	at b0.w.a(SourceFile:48)
	at b0.x.c(SourceFile:140)
	at A0.w0.a(SourceFile:3)
	at g0.e.l(SourceFile:463)
	at B0.X0.E(SourceFile:22)
	at B0.Z0.i(SourceFile:40)
	at B0.Z0.c(SourceFile:14)
	at A0.j0.C0(SourceFile:5)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at B0.A.dispatchDraw(SourceFile:69)
	at android.view.View.draw(Unknown Source:70)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:198)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:69)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:69)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(Unknown Source:27)
	at android.view.ThreadedRenderer.updateRootDisplayList(Unknown Source:10)
	at android.view.ThreadedRenderer.draw(Unknown Source:7)
	at android.view.ViewRootImpl.draw(Unknown Source:404)
	at android.view.ViewRootImpl.performDraw(Unknown Source:112)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:3085)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:7)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:110)
	at android.view.Choreographer.doFrame(Unknown Source:524)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

```

**Comment by hushenghao** [comment]
This issue has been fixed in the [latest beta version](https://www.pgyer.com/eggs)

**Comment by hushenghao** [comment]
R8 retrace stack:

```log
java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.InlineClassHelperKt.throwIllegalArgumentException(InlineClassHelper.kt:26)
	at androidx.compose.ui.graphics.ColorKt.Color(Color.kt:722)
	at androidx.compose.ui.graphics.Color.copy-wmQWz5c(Color.kt:259)
	at androidx.compose.ui.graphics.Color.copy-wmQWz5c$default(Color.kt:254)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.modulate-5vOe2sY(CanvasDrawScope.kt:713)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.configurePaint-2qPWKa0(CanvasDrawScope.kt:645)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.configurePaint-2qPWKa0$default(CanvasDrawScope.kt:635)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawRect-n-J9OG0(CanvasDrawScope.kt:195)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawRect-n-J9OG0(LayoutNodeDrawScope.kt)
	at androidx.compose.ui.graphics.drawscope.DrawScope.drawRect-n-J9OG0$default(DrawScope.kt:487)
	at com.t8rin.modalsheet.ModalSheetLayoutKt$Scrim$1$1.invoke(ModalSheetLayout.kt:451)
	at com.t8rin.modalsheet.ModalSheetLayoutKt$Scrim$1$1.invoke(ModalSheetLayout.kt:450)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:127)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:110)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:89)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:434)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:280)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:964)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:280)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:964)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:964)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:280)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:964)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:453)
	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:452)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2439)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:452)
	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:450)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:341)
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:283)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:418)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:964)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:431)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:423)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:964)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1515)
	at android.view.View.draw(Unknown Source:70)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:198)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:69)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:69)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(Unknown Source:27)
	at android.view.ThreadedRenderer.updateRootDisplayList(Unknown Source:10)
	at android.view.ThreadedRenderer.draw(Unknown Source:7)
	at android.view.ViewRootImpl.draw(Unknown Source:404)
	at android.view.ViewRootImpl.performDraw(Unknown Source:112)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:3085)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:7)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:110)
	at android.view.Choreographer.doFrame(Unknown Source:524)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
```

The issue occurred on the **Timeline** ModalSheet, which has been updated to `com.t8rin.modalsheet.ModalSheet` replace with `androidx.compose.material3.ModalBottomSheet` to implement
