### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by alphime** [hushenghao/AndroidEasterEggs#258]
https://github.com/hushenghao/AndroidEasterEggs/assets/109449075/a2514fe8-a405-4003-bd49-0617089f79e3

```
Device: Mi 9 Lite (Xiaomi - pyxis), SDK: 34 (14), App: 2.5.0 (40)

java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.a.u(SourceFile:3)
	at androidx.compose.ui.graphics.a.b(SourceFile:484)
	at k0.v.b(SourceFile:17)
	at m0.c.a(SourceFile:18)
	at m0.c.j(SourceFile:44)
	at A0.L.j(SourceFile:16)
	at m0.g.j(SourceFile:60)
	at v.q.a(SourceFile:37)
	at v.q.l(SourceFile:10)
	at h0.e.e(SourceFile:3)
	at A0.L.b(SourceFile:52)
	at A0.j0.E0(SourceFile:55)
	at A0.j0.C0(SourceFile:30)
	at A0.E.U0(SourceFile:6)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at A0.E.U0(SourceFile:6)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at A0.E.U0(SourceFile:6)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at v.U.b(SourceFile:324)
	at v.U.c(SourceFile:55)
	at C3.e.u(SourceFile:114)
	at b0.w.a(SourceFile:48)
	at b0.x.c(SourceFile:140)
	at A0.w0.a(SourceFile:3)
	at g0.e.l(SourceFile:463)
	at B0.X0.E(SourceFile:22)
	at B0.Z0.i(SourceFile:40)
	at B0.Z0.c(SourceFile:14)
	at A0.j0.C0(SourceFile:5)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at A0.y.U0(SourceFile:28)
	at A0.j0.E0(SourceFile:9)
	at A0.j0.C0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at B0.A.dispatchDraw(SourceFile:69)
	at android.view.View.draw(View.java:24193)
	at android.view.View.updateDisplayListIfDirty(View.java:23056)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
	at android.view.View.updateDisplayListIfDirty(View.java:23012)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
	at android.view.View.updateDisplayListIfDirty(View.java:23012)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:706)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:712)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:810)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5234)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4900)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4049)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:938)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8528)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

**Comment by hushenghao** [comment]
#250
