### ISSUE TITLE
[Bug] App Crash: java.lang.IllegalArgumentException: Manifest shortcut ID=android_34 may not be manipulated via APIs

### ISSUE THREAD

**Issue by xiangmingzi-cmd** [hushenghao/AndroidEasterEggs#347]
```
Device: M2012K11AC (Redmi - alioth), SDK: 13 (33), App: 2.6.4 (47)

java.lang.IllegalArgumentException: Manifest shortcut ID=android_34 may not be manipulated via APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.content.pm.IShortcutService$Stub$Proxy.pushDynamicShortcut(IShortcutService.java:1025)
	at android.content.pm.ShortcutManager.pushDynamicShortcut(ShortcutManager.java:784)
	at p0.n.f(SourceFile:1)
	at B2.a.run(SourceFile:577)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.ShortcutPackage.ensureNotImmutable(ShortcutPackage.java:297)
	at com.android.server.pm.ShortcutPackage.ensureNotImmutable(ShortcutPackage.java:303)
	at com.android.server.pm.ShortcutService.pushDynamicShortcut(ShortcutService.java:2244)
	at android.content.pm.IShortcutService$Stub.onTransact(IShortcutService.java:561)
	at android.os.Binder.execTransactInternal(Binder.java:1285)


```

**Comment by hushenghao** [comment]
Update Beta APK and test
