### ISSUE TITLE
[Bug] App Crash: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference


### ISSUE THREAD

**Issue by ZpPaul-Gor** [hushenghao/AndroidEasterEggs#394]
```
Device: 23117RA68G (Redmi - emerald), SDK: 14 (34), App: 3.1.0-beta02 (51), VcsRevision: 3892e3

java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$1(WindowOnBackInvokedDispatcher.java:353)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$jWVwe-YeLRxW3tAMLuWZynG6e1k(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

```

**Comment by hushenghao** [comment]
This does not seem to be a stable crash, can you provide the steps for recurrence

**Comment by ytheekshana** [comment]
I have the same. Happening only on Mi Devices

**Comment by hushenghao** [comment]
> I have the same. Happening only on Mi Devices

How did it happen, and was there a repetition step?

**Comment by hushenghao** [comment]
[issuetracker#372064005](https://issuetracker.google.com/issues/372064005)
